CREATE DATABASE poketrash CHARACTER SET 'utf8';

USE poketrash;

CREATE TABLE `pokedex` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pkmName` VARCHAR(255) NOT NULL,
  `type1` VARCHAR(255),
  `type2` VARCHAR(255),
  `evolution1` SMALLINT,
  `evolution2` SMALLINT,
  `bio` MEDIUMTEXT,
  `img` VARCHAR(255),
  PRIMARY KEY (Id)
);

CREATE TABLE `users` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE `profile` (
  `avatar` VARCHAR(255),
  `favorite` SMALLINT,
  `bio` MEDIUMTEXT,
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id)
);

CREATE Table `stats` (
  pkm_id int(11) NOT NULL,
  hp int(11) DEFAULT NULL,
  atk int(11) DEFAULT NULL,
  def int(11) DEFAULT NULL,
  atk_spe int(11) DEFAULT NULL,
  def_spe int(11) DEFAULT NULL,
  speed int(11) DEFAULT NULL,
  PRIMARY KEY (pkm_id)
);

INSERT INTO `users` (`id`,`username`,`password`,`email`)
VALUES ('1','DracaufeuDu69','abc9cdee0d7a88eb000f26d1b3b8e60c806a86b15560809fda54d4ffe64656f36054b96bd3373472c670094e37bdcdda6ef7c43f12a79539b954cd9962362663','Sachatte@gmail.com');

INSERT INTO `pokedex` (`id`,`pkmName`,`type1`,`type2`,`evolution1`,`evolution2`,`bio`,`img`)
VALUES 
  ('1','Bulbizarre','Plante','Poison','2','3',"Bulbizarre est un petit Pokémon quadrupède vert. Il possède une grande fleur sur le dos qui grandit en même temps que lui. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Il possède une queue courte et épaisse. Ses pattes sont munies de trois griffes. Il possède une tache jaune sur le ventre. Il est le premier Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/001.png'),
  ('2','Herbizarre','Plante','Poison',NULL,'3',"Herbizarre est un Pokémon quadrupède vert. Il possède une grande fleur sur le dos qui grandit en même temps que lui. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Il possède une queue courte et épaisse. Ses pattes sont munies de trois griffes. Il possède une tache jaune sur le ventre. Il est le premier Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/002.png'),
  ('3','Florizarre','Plante','Poison',NULL,NULL,"Florizarre est un Pokémon quadrupède vert. Il possède une grande fleur sur le dos qui grandit en même temps que lui. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Il possède une queue courte et épaisse. Ses pattes sont munies de trois griffes. Il possède une tache jaune sur le ventre. Il est le premier Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/003.png'),
  ('4','Salamèche','Feu',NULL,'5','6',"Salamèche est un Pokémon bipède de couleur orange. Il possède une crête de feu sur la tête ainsi qu'une flamme au bout de la queue. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le quatrième Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/004.png'),
  ('5','Reptincel','Feu',NULL,NULL,'6',"Reptincel est un Pokémon bipède de couleur orange. Il possède une crête de feu sur la tête ainsi qu'une flamme au bout de la queue. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le quatrième Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/005.png'),
  ('6','Dracaufeu','Feu','Vol',NULL,NULL,"Dracaufeu est un Pokémon bipède de couleur orange. Il possède une crête de feu sur la tête ainsi qu'une flamme au bout de la queue. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le quatrième Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/006.png'),
  ('7','Carapuce','Eau',NULL,'8','9',"Carapuce est un Pokémon bipède de couleur bleue. Il possède une carapace de couleur brune sur le dos. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le septième Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/007.png'),
  ('8','Carabaffe','Eau',NULL,NULL,'9',"Carabaffe est un Pokémon bipède de couleur bleue. Il possède une carapace de couleur brune sur le dos. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le septième Pokémon du Pokédex de Kanto.",'https://www.serebii.net/pokemongo/pokemon/008.png'),
  ('9','Tortank','Eau', NULL,NULL,NULL,'Tortank est un Pokémon bipède de couleur bleue. Il possède une carapace de couleur brune sur le dos. Ses yeux sont toujours fermés, et il est endormi la plupart du temps. Ses pattes sont munies de trois griffes. Il est le septième Pokémon du Pokédex de Kanto.','https://www.serebii.net/pokemongo/pokemon/009.png'),
  ('10', 'Chenipan', 'Insecte', NULL, '11', '12', "Chenipan est un Pokémon rampant de couleur verte. Il se nourrit de feuilles et possède une corne sur la tête. Il est le dixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/010.png'),
  ('11', 'Chrysacier', 'Insecte', NULL, NULL, '12', "Chrysacier est la forme évoluée de Chenipan. Il est de couleur vert clair et possède une carapace dure. Il est le onzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/011.png'),
  ('12', 'Papilusion', 'Insecte', 'Vol', NULL, NULL, "Papilusion est un Pokémon ailé aux couleurs vives. Ses ailes sont recouvertes de poussière d'aile qui donne des couleurs différentes en fonction de l'angle de la lumière. Il est le douzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/012.png'),
  ('13', 'Aspicot', 'Insecte', 'Poison', '14', '15', "Aspicot est un Pokémon rampant de couleur violet. Il possède une corne sur la tête et peut libérer des poisons. Il est le treizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/013.png'),
  ('14', 'Coconfort', 'Insecte', 'Poison', NULL, '15', "Coconfort est la forme évoluée d'Aspicot. Il est enveloppé dans un cocon protecteur. Il est le quatorzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/014.png'),
  ('15', 'Dardargnan', 'Insecte', 'Poison', NULL, NULL, "Dardargnan est un Pokémon ailé de grande taille. Il possède des aiguillons toxiques sur ses pattes et son abdomen. Il est le quinzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/015.png'),
  ('16', 'Roucool', 'Normal', 'Vol', '17', '18', "Roucool est un petit Pokémon volant. Il a un plumage marron et blanc et peut atteindre des vitesses élevées en volant. Il est le seizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/016.png'),
  ('17', 'Roucoups', 'Normal', 'Vol', NULL, '19', "Roucoups est la forme évoluée de Roucool. Il a un plumage plus développé et est capable de voler sur de longues distances. Il est le dix-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/017.png'),
  ('18', 'Roucarnage', 'Normal', 'Vol', NULL, NULL, "Roucarnage est un Pokémon majestueux avec un grand envergure. Il est le dix-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/018.png'),
  ('19', 'Rattata', 'Normal', NULL, '20', NULL, "Rattata est un petit Pokémon rongeur. Il est actif la nuit et peut être trouvé dans de nombreux habitats. Il est le dix-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/019.png'),
  ('20', 'Rattatac', 'Normal', NULL, NULL, NULL, "Rattatac est la forme évoluée de Rattata. Il est plus grand et plus fort que sa forme précédente. Il est le vingtième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/020.png'),
  ('21', 'Piafabec', 'Normal', 'Vol', '22', NULL, "Piafabec crie tellement fort qu'il peut être entendu à 1km de distance. Ces Pokémon se préviennent d'un danger en entonnant une mélopée très aiguë, qu'ils se renvoient les uns les autres, comme un écho.", 'https://www.serebii.net/pokemongo/pokemon/021.png'),
  ('22', 'Rapasdepic', 'Normal', 'Vol', NULL, NULL, "On reconnaît un Rapasdepic à son long cou et à son bec allongé. Ces attributs lui permettent d'attraper facilement ses proies dans la terre ou dans l'eau. Il bouge son bec long et fin avec une grande agilité.", 'https://www.serebii.net/pokemongo/pokemon/022.png'),
  ('23', 'Abo', 'Poison', NULL, '24', NULL, "Abo s'enroule en spirale pour dormir. Sa tête reste relevée de telle sorte que cette position lui permette de réagir rapidement si une menace survenait.", 'https://www.serebii.net/pokemongo/pokemon/023.png'),
  ('24', 'Arbok', 'Poison', NULL, NULL, NULL, "Ce Pokémon doté d'une force extraordinaire peut étrangler ses proies avec son corps. Il peut même écraser des tonneaux métalliques. Une fois sous l'étreinte d'Arbok, il est impossible de lui échapper.", 'https://www.serebii.net/pokemongo/pokemon/024.png'),
  ('25', 'Pikachu', 'Électrik', NULL, '26', NULL, "Chaque fois que Pikachu découvre quelque chose de nouveau, il envoie un arc électrique. Lorsqu'on tombe sur une Baie carbonisée, ça signifie sans doute qu'un de ces Pokémon a envoyé une charge trop forte.", 'https://www.serebii.net/pokemongo/pokemon/025.png'),
  ('26', 'Raichu', 'Électrik', NULL, NULL, NULL, "Si ses joues contiennent trop d'électricité, Raichu plante sa queue dans le sol pour se décharger. On trouve des parcelles de terre brûlée à proximité du nid de ce Pokémon.", 'https://www.serebii.net/pokemongo/pokemon/026.png'),
  ('27', 'Sabelette', 'Sol', NULL, '28', NULL, "Le corps de Sabelette lui permet d'économiser l'eau qu'il absorbe, afin de survivre longtemps dans le désert. Ce Pokémon s'enroule sur lui-même pour se protéger de ses ennemis.", 'https://www.serebii.net/pokemongo/pokemon/027.png'),
  ('28', 'Sablaireau', 'Sol', NULL, NULL, NULL, "Le corps de Sablaireau est recouvert de pointes très dures, qui sont des extensions de sa peau. Une fois par an, ce Pokémon mue et les vieilles pointes tombent, remplacées par de nouvelles.", 'https://www.serebii.net/pokemongo/pokemon/028.png'),
  ('29', 'Nidoran♀', 'Poison', NULL, '30', '31', "Nidoran♀ est couvert de pointes qui secrètent un poison puissant. On pense que ce petit Pokémon a développé ces pointes pour se défendre. Lorsqu'il est en colère, une horrible toxine sort de sa corne.", 'https://www.serebii.net/pokemongo/pokemon/029.png'),
  ('30', 'Nidorina', 'Poison', NULL, NULL, '32', "Lorsqu'un Nidorina est avec ses amis ou sa famille, il replie ses pointes pour ne pas blesser ses proches. Ce Pokémon devient vite nerveux lorsqu'il est séparé de son groupe.", 'https://www.serebii.net/pokemongo/pokemon/030.png'),
  ('31', 'Nidoqueen', 'Poison', 'Sol', NULL, NULL, "Le corps de Nidoqueen est protégé par des écailles extrêmement dures. Il aime envoyer ses ennemis voler en leur fonçant dessus. Ce Pokémon utilise toute sa puissance lorsqu'il protège ses petits.", 'https://www.serebii.net/pokemongo/pokemon/031.png'),
  ('32', 'Nidoran♂', 'Poison', NULL, '33', '34', "Nidoran♂ a développé des muscles pour bouger ses oreilles. Ainsi, il peut les orienter à sa guise. Ce Pokémon peut entendre le plus discret des bruits.", 'https://www.serebii.net/pokemongo/pokemon/032.png'),
  ('33', 'Nidorino', 'Poison', NULL, NULL, '35', "Nidorino dispose d'une corne plus dure que du diamant. S'il sent une présence hostile, toutes les pointes de son dos se hérissent d'un coup, puis il défie son ennemi.", 'https://www.serebii.net/pokemongo/pokemon/33.png'),
  ('34', 'Nidoking', 'Poison', 'Sol', NULL, NULL, "L'épaisse queue de Nidoking est d'une puissance incroyable. En un seul coup, il peut renverser une tour métallique. Lorsque ce Pokémon se déchaîne, plus rien ne peut l'arrêter.", 'https://www.serebii.net/pokemongo/pokemon/034.png'),
  ('35', 'Mélofée', 'Fée', NULL, '36', NULL, "Mélofée est un Pokémon de type Fée. Il est connu pour sa douceur et son apparence mignonne. Il est le trente-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/035.png'),
  ('36', 'Mélodelfe', 'Fée', NULL, NULL, NULL, "Mélodelfe est la forme évoluée de Mélofée. Il continue de répandre la joie et la douceur. Il est le trente-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/036.png'),
  ('37', 'Goupix', 'Feu', NULL, '38', NULL, "Goupix est un Pokémon de type Feu. Il possède une fourrure chaude qui le protège du froid. Il est le trente-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/037.png'),
  ('38', 'Feunard', 'Feu', NULL, NULL, NULL, "Feunard est la forme évoluée de Goupix. Sa fourrure devient plus épaisse et il gagne en puissance. Il est le quarantième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/038.png'),
  ('39', 'Rondoudou', 'Normal', 'Fée', '40', NULL, "Rondoudou est un Pokémon rond et rose de type Normal et Fée. Il aime chanter des berceuses. Il est le quarante-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/039.png'),
  ('40', 'Grodoudou', 'Normal', 'Fée', NULL, NULL, "Grodoudou est la forme évoluée de Rondoudou. Il continue de répandre de la joie avec sa musique. Il est le quarante-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/040.png'),
  ('41', 'Nosferapti', 'Poison', 'Vol', '42', NULL, "Nosferapti est un Pokémon de type Poison et Vol. Il est actif la nuit et se nourrit du sang de ses proies. Il est le cinquantième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/041.png'),
  ('42', 'Nosferalto', 'Poison', 'Vol', NULL, NULL, "Nidorino est la forme évoluée de Nidoran♂. Il possède une corne plus développée et est plus puissant. Il est le quarante-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/042.png'),
  ('43', 'Mystherbe', 'Plante', 'Poison', '44', '45', "Pendant la journée, Mystherbe s'enterre dans le sol pour absorber avec son corps tout entier les nutriments présents dans la terre. Plus le sol est fertile, plus ses feuilles sont brillantes.", 'https://www.serebii.net/pokemongo/pokemon/043.png'),
  ('44', 'Ortide', 'Plante', 'Poison', '45', NULL, "La plupart du temps, Ortide dégage un parfum immonde du pistil de sa fleur. Lorsqu'il se sent en danger, la puanteur est encore pire. Lorsque ce Pokémon se sent bien en sécurité, il ne dégage aucune odeur nauséabonde.", 'https://www.serebii.net/pokemongo/pokemon/044.png'),
  ('45', 'Rafflesia', 'Plante', 'Poison', NULL, NULL, "Le pollen toxique de Rafflesia déclenche d'affreuses réactions allergiques. C'est pourquoi il est conseillé de ne jamais s'approcher des jolies fleurs trouvées dans la jungle, même lorsqu'elles sont magnifiques.", 'https://www.serebii.net/pokemongo/pokemon/045.png'),
  ('46', 'Paras', 'Insecte', 'Plante', '47', NULL, "Paras accueille des champignons parasites appelés tochukaso qui poussent sur son dos. Ils grandissent grâce aux nutriments trouvés sur le dos de ce Pokémon Insecte.", 'https://www.serebii.net/pokemongo/pokemon/046.png'),
  ('47', 'Parasect', 'Insecte', 'Plante', NULL, NULL, "On sait que les Parasect vivent en groupe dans les grands arbres et se nourrissent des nutriments contenus dans le tronc et les racines. Lorsqu'un arbre infesté meurt, ils se précipitent vers le prochain.", 'https://www.serebii.net/pokemongo/pokemon/047.png'),
  ('48', 'Mimitos', 'Insecte', 'Poison', '49', NULL, "On raconte que Mimitoss a évolué avec une fourrure de poils fins et drus qui protège son corps tout entier. Il est doté de grands yeux capables de repérer ses proies, même minuscules.", 'https://www.serebii.net/pokemongo/pokemon/048.png'),
  ('49', 'Aéromite', 'Insecte', 'Poison', NULL, NULL, "Aéromite est la forme évoluée de Aspicot. Il vole en utilisant ses ailes. Il est le cinquante et unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/049.png'),
  ('50', 'Taupiqueur', 'Sol', NULL, '51', NULL, "Les Taupiqueur sont élevés dans la plupart des fermes. En effet, lorsque ce Pokémon creuse quelque part, le sol est comme labouré, prêt à recevoir les semences. On peut alors y planter de délicieux légumes.", 'https://www.serebii.net/pokemongo/pokemon/050.png'),
  ('51', 'Triopikeur', 'Sol', NULL, NULL, NULL, "Les Triopikeur sont en fait des triplés qui ont émergé du même corps. C'est pourquoi chaque triplé pense exactement comme les deux autres. Ils creusent inlassablement, dans une coopération parfaite.", 'https://www.serebii.net/pokemongo/pokemon/051.png'),
  ('52', 'Miaouss', 'Normal', NULL, '53', NULL, "Miaouss peut rentrer ses griffes dans ses pattes pour rôder gracieusement sans laisser de traces. Étrangement, ce Pokémon raffole des pièces d'or qui brillent à la lumière.", 'https://www.serebii.net/pokemongo/pokemon/052.png'),
  ('53', 'Persian', 'Normal', NULL, NULL, NULL, "Persian est un Pokémon de type Normal. Il est connu pour sa grâce et sa beauté. Il est le cinquante-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/053.png'),
  ('54', 'Psykokwak', 'Eau', NULL, '55', NULL, "Psykokwak est un Pokémon de type Eau. Il est connu pour sa tête ronde et son bec jaune. Il est le cinquante-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/054.png'),
  ('55', 'Akwakwak', 'Eau', NULL, NULL, NULL, "Akwakwak est la forme évoluée de Psykokwak. Il est connu pour sa grande taille et sa force. Il est le cinquante-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/055.png'),
  ('56', 'Férosinge', 'Combat', NULL, '57', NULL, "Férosinge est un Pokémon de type Combat. Il est connu pour sa force et sa rapidité. Il est le cinquante-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/056.png'),
  ('57', 'Colossinge', 'Combat', NULL, NULL, NULL, "Colossinge est la forme évoluée de Férosinge. Il est connu pour sa force et sa puissance. Il est le cinquante-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/057.png'),
  ('58', 'Caninos', 'Feu', NULL, '59', NULL, "Caninos est un Pokémon de type Feu. Il est connu pour sa loyauté et son courage. Il est le cinquante-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/058.png'),
  ('59', 'Arcanin', 'Feu', NULL, NULL, NULL, "Arcanin est la forme évoluée de Caninos. Il est connu pour sa force et sa rapidité. Il est le cinquante-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/059.png'),
  ('60', 'Ptitard', 'Eau', NULL, '61', NULL, "Ptitard est un Pokémon de type Eau. Il est connu pour sa petite taille et sa queue en forme de spirale. Il est le soixantième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/060.png'),
  ('61', 'Têtarte', 'Eau', NULL, '62', NULL, "Têtarte est la forme évoluée de Ptitard. Il est connu pour sa force et sa puissance. Il est le soixante-et-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/061.png'),
  ('62', 'Tartard', 'Eau', 'Combat', NULL, NULL, "Tartard est la forme évoluée de Têtarte. Il est connu pour sa force et sa puissance. Il est le soixante-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/062.png'),
  ('63', 'Abra', 'Psy', NULL, '64', NULL, "Abra est un Pokémon de type Psy. Il est connu pour sa capacité à se téléporter. Il est le soixante-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/063.png'),
  ('64', 'Kadabra', 'Psy', NULL, '65', NULL, "Kadabra est la forme évoluée d'Abra. Il est connu pour sa grande intelligence et ses pouvoirs psychiques. Il est le soixante-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/064.png'),
  ('65', 'Alakazam', 'Psy', NULL, NULL, NULL, "Alakazam est la forme évoluée de Kadabra. Il est connu pour sa grande intelligence et ses pouvoirs psychiques. Il est le soixante-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/065.png'),
  ('66', 'Machoc', 'Combat', NULL, '67', NULL, "Machoc est un Pokémon de type Combat. Il est connu pour sa force et sa puissance. Il est le soixante-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/066.png'),
  ('67', 'Machopeur', 'Combat', NULL, '68', NULL, "Machopeur est la forme évoluée de Machoc. Il est connu pour sa force et sa puissance. Il est le soixante-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/067.png'),
  ('68', 'Mackogneur', 'Combat', NULL, NULL, NULL, "Mackogneur est la forme évoluée de Machopeur. Il est connu pour sa force et sa puissance. Il est le soixante-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/068.png'),
  ('69', 'Chétiflor', 'Plante', 'Poison', '70', NULL, "Chétiflor est un Pokémon de type Plante et Poison. Il est connu pour sa capacité à endormir ses ennemis. Il est le soixante-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/069.png'),
  ('70', 'Boustiflor', 'Plante', 'Poison', '71', NULL, "Boustiflor est la forme évoluée de Chétiflor. Il est connu pour sa capacité à endormir ses ennemis. Il est le soixante-dixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/070.png'),
  ('71', 'Empiflor', 'Plante', 'Poison', NULL, NULL, "Empiflor est la forme évoluée de Chétiflor. Il est connu pour sa capacité à endormir ses ennemis. Il est le soixante et onzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/071.png'),
  ('72', 'Tentacool', 'Eau', 'Poison', '73', NULL, "Tentacool est un Pokémon de type Eau et Poison. Il est connu pour sa capacité à se camoufler. Il est le soixante-douzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/072.png'),
  ('73', 'Tentacruel', 'Eau', 'Poison', NULL, NULL, "Tentacruel est la forme évoluée de Tentacool. Il est connu pour sa grande taille et sa force. Il est le soixante-treizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/073.png'),
  ('74', 'Racaillou', 'Roche', 'Sol', '75', '76', "Racaillou est un Pokémon de type Roche et Sol. Il est connu pour sa grande résistance. Il est le soixante-quatorzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/074.png'),
  ('75', 'Gravalanch', 'Roche', 'Sol', '76', NULL, "Gravalanch est la forme évoluée de Racaillou. Il est connu pour sa grande résistance et sa force. Il est le soixante-quinzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/075.png'),
  ('76', 'Grolem', 'Roche', 'Sol', NULL, NULL, "Grolem est la forme évoluée de Gravalanch. Il est connu pour sa grande résistance et sa force. Il est le soixante-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/076.png'),
  ('77', 'Ponyta', 'Feu', NULL, '78', NULL, "Ponyta est un Pokémon de type Feu. Il est connu pour sa rapidité et sa beauté. Il est le soixante-dix-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/077.png'),
  ('78', 'Galopa', 'Feu', NULL, NULL, NULL, "Galopa est la forme évoluée de Ponyta. Il est connu pour sa rapidité et sa beauté. Il est le soixante-dix-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/078.png'),
  ('79', 'Ramoloss', 'Eau', 'Psy', '80', NULL, "Ramoloss est un Pokémon de type Eau et Psy. Il est connu pour sa lenteur et sa capacité à dormir debout. Il est le soixante-dix-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/079.png'),
  ('80', 'Flagadoss', 'Eau', 'Psy', NULL, NULL, "Flagadoss est la forme évoluée de Ramoloss. Il est connu pour sa lenteur et sa capacité à dormir debout. Il est le quatre-vingtième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/080.png'),
  ('81', 'Magnéti', 'Électrik', 'Acier', '82', NULL, "Magnéti est un Pokémon de type Électrik et Acier. Il est connu pour sa capacité à attirer les métaux. Il est le quatre-vingt-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/081.png'),
  ('82', 'Magnéton', 'Électrik', 'Acier', NULL, NULL, "Magnéton est la forme évoluée de Magnéti. Il est connu pour sa capacité à attirer les métaux. Il est le quatre-vingt-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/082.png'),
  ('83', 'Canarticho', 'Normal', 'Vol', NULL, NULL, "Canarticho est un Pokémon de type Normal et Vol. Il est connu pour son bec long et fin. Il est le quatre-vingt-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/083.png'),
  ('84', 'Doduo', 'Normal', 'Vol', '85', NULL, "Doduo est un Pokémon de type Normal et Vol. Il est connu pour sa capacité à courir très vite. Il est le quatre-vingt-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/084.png'),
  ('85', 'Dodrio', 'Normal', 'Vol', NULL, NULL, "Dodrio est la forme évoluée de Doduo. Il est connu pour sa capacité à courir très vite. Il est le quatre-vingt-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/085.png'),
  ('86', 'Otaria', 'Eau', NULL, '87', NULL, "Otaria est un Pokémon de type Eau. Il est connu pour sa capacité à nager très vite. Il est le quatre-vingt-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/086.png'),
  ('87', 'Lamantine', 'Eau', 'Glace', NULL, NULL, "Lamantine est la forme évoluée d'Otaria. Il est connu pour sa capacité à nager très vite et sa résistance au froid. Il est le quatre-vingt-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/087.png'),
  ('88', 'Tadmorv', 'Poison', NULL, '89', NULL, "Tadmorv est un Pokémon de type Poison. Il est connu pour sa capacité à se nourrir de déchets. Il est le quatre-vingt-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/088.png'),
  ('89', 'Grotadmorv', 'Poison', NULL, NULL, NULL, "Grotadmorv est la forme évoluée de Tadmorv. Il est connu pour sa capacité à se nourrir de déchets. Il est le quatre-vingt-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/089.png'),
  ('90', 'Kokiyas', 'Eau', NULL, '91', NULL, "Kokiyas est un Pokémon de type Eau. Il est connu pour sa carapace dure. Il est le quatre-vingt-dixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/090.png'),
  ('91', 'Crustabri', 'Eau', 'Glace', NULL, NULL, "Crustabri est un Pokémon de type Eau et Glace. Il est connu pour sa carapace dure. Il est le quatre-vingt-onzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/091.png'),
  ('92', 'Fantominus', 'Spectre', 'Poison', '93', '94', "Fantominus est un Pokémon de type Spectre et Poison. Il est connu pour sa capacité à se rendre invisible. Il est le quatre-vingt-douzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/092.png'),
  ('93', 'Spectrum', 'Spectre', 'Poison', '94', NULL, "Spectrum est la forme évoluée de Fantominus. Il est connu pour sa capacité à se rendre invisible. Il est le quatre-vingt-treizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/093.png'),
  ('94', 'Ectoplasma', 'Spectre', 'Poison', NULL, NULL, "Ectoplasma est la forme évoluée de Spectrum. Il est connu pour sa capacité à se rendre invisible. Il est le quatre-vingt-quatorzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/094.png'),
  ('95', 'Onix', 'Roche', 'Sol', NULL, NULL, "Onix est un Pokémon de type Roche et Sol. Il est connu pour sa grande taille et sa force. Il est le quatre-vingt-quinzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/095.png'),
  ('96', 'Soporifik', 'Psy', NULL, '97', NULL, "Soporifik est un Pokémon de type Psy. Il est connu pour sa capacité à endormir ses ennemis. Il est le quatre-vingt-seizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/096.png'),
  ('97', 'Hypnomade', 'Psy', NULL, NULL, NULL, "Hypnomade est la forme évoluée de Soporifik. Il est connu pour sa capacité à endormir ses ennemis. Il est le quatre-vingt-dix-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/097.png'),
  ('98', 'Krabby', 'Eau', NULL, '99', NULL, "Krabby est un Pokémon de type Eau. Il est connu pour sa pince puissante. Il est le quatre-vingt-dix-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/098.png'),
  ('99', 'Krabboss', 'Eau', NULL, NULL, NULL, "Krabboss est la forme évoluée de Krabby. Il est connu pour sa pince puissante. Il est le quatre-vingt-dix-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/099.png'),
  ('100', 'Voltorbe', 'Électrik', NULL, '101', NULL, "Voltorbe est un Pokémon de type Électrik. Il est connu pour sa forme sphérique. Il est le centième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/100.png'),
  ('101', 'Électrode', 'Électrik', NULL, NULL, NULL, "Électrode est la forme évoluée de Voltorbe. Il est connu pour sa forme sphérique. Il est le cent-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/101.png'),
  ('102', 'Noeunoeuf', 'Plante', 'Psy', '103', NULL, "Noeunoeuf est un Pokémon de type Plante et Psy. Il est connu pour sa capacité à se régénérer. Il est le cent-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/102.png'),
  ('103', 'Noadkoko', 'Plante', 'Psy', NULL, NULL, "Noadkoko est la forme évoluée de Noeunoeuf. Il est connu pour sa capacité à se régénérer. Il est le cent-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/103.png'),
  ('104', 'Osselait', 'Sol', NULL, '105', NULL, "Osselait est un Pokémon de type Sol. Il est connu pour sa tête d'os. Il est le cent-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/104.png'),
  ('105', 'Ossatueur', 'Sol', NULL, NULL, NULL, "Ossatueur est la forme évoluée d'Osselait. Il est connu pour sa tête d'os. Il est le cent-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/105.png'),
  ('106', 'Kicklee', 'Combat', NULL, NULL, NULL, "Kicklee est un Pokémon de type Combat. Il est connu pour ses jambes puissantes. Il est le cent-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/106.png'),
  ('107', 'Tygnon', 'Combat', NULL, NULL, NULL, "Tygnon est un Pokémon de type Combat. Il est connu pour ses mouvements de karaté. Il est le cent-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/107.png'),
  ('108', 'Excelangue', 'Normal', NULL, NULL, NULL, "Excelangue est un Pokémon de type Normal. Il est connu pour sa longue langue. Il est le cent-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/108.png'),
  ('109', 'Smogo', 'Poison', NULL, '110', NULL, "Smogo est un Pokémon de type Poison. Il est connu pour sa capacité à empoisonner ses ennemis. Il est le cent-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/109.png'),
  ('110', 'Smogogo', 'Poison', NULL, NULL, NULL, "Smogogo est la forme évoluée de Smogo. Il est connu pour sa capacité à empoisonner ses ennemis. Il est le cent-dixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/110.png'),
  ('111', 'Rhinocorne', 'Sol', 'Roche', '112', NULL, "Rhinocorne est un Pokémon de type Sol et Roche. Il est connu pour sa corne puissante. Il est le cent-onzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/111.png'),
  ('112', 'Rhinoféros', 'Sol', 'Roche', NULL, NULL, "Rhinoféros est la forme évoluée de Rhinocorne. Il est connu pour sa corne puissante. Il est le cent-douzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/112.png'),
  ('113', 'Leveinard', 'Normal', NULL, NULL, NULL, "Leveinard est un Pokémon de type Normal. Il est connu pour sa grande capacité de guérison. Il est le cent-treizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/113.png'),
  ('114', 'Saquedeneu', 'Plante', NULL, NULL, NULL, "Saquedeneu est un Pokémon de type Plante. Il est connu pour sa queue en forme de noix. Il est le cent-quatorzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/114.png'),
  ('115', 'Kangourex', 'Normal', NULL, NULL, NULL, "Kangourex est un Pokémon de type Normal. Il est connu pour sa poche ventrale. Il est le cent-quinzième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/115.png'),
  ('116', 'Hypotrempe', 'Eau', NULL, '117', NULL, "Hypotrempe est un Pokémon de type Eau. Il est connu pour sa petite taille. Il est le cent-seizième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/116.png'),
  ('117', 'Hypocéan', 'Eau', NULL, NULL, NULL, "Hypocéan est la forme évoluée d'Hypotrempe. Il est connu pour sa grande taille. Il est le cent-dix-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/117.png'),
  ('118', 'Poissirène', 'Eau', NULL, '119', NULL, "Poissirène est un Pokémon de type Eau. Il est connu pour sa queue en forme de ruban. Il est le cent-dix-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/118.png'),
  ('119', 'Poissoroy', 'Eau', NULL, NULL, NULL, "Poissoroy est la forme évoluée de Poissirène. Il est connu pour sa queue en forme de ruban. Il est le cent-dix-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/119.png'),
  ('120', 'Stari', 'Eau', 'Psy', '121', NULL, "Stari est un Pokémon de type Eau et Psy. Il est connu pour sa forme en étoile. Il est le cent-vingtième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/120.png'),
  ('121', 'Staross', 'Eau', 'Psy', NULL, NULL, "Staross est la forme évoluée de Stari. Il est connu pour sa forme en étoile. Il est le cent-vingt-et-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/121.png'),
  ('122', 'M. Mime', 'Psy', 'Fée', NULL, NULL, "M. Mime est un Pokémon de type Psy et Fée. Il est connu pour sa capacité à créer des barrières. Il est le cent-vingt-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/122.png'),
  ('123', 'Insécateur', 'Insecte', 'Vol', NULL, NULL, "Insécateur est un Pokémon de type Insecte et Vol. Il est connu pour sa grande vitesse. Il est le cent-vingt-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/123.png'),
  ('124', 'Lippoutou', 'Glace', 'Psy', NULL, NULL, "Lippoutou est un Pokémon de type Glace et Psy. Il est connu pour sa grâce et sa beauté. Il est le cent-vingt-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/124.png'),
  ('125', 'Élektek', 'Électrik', NULL, NULL, NULL, "Élektek est un Pokémon de type Électrik. Il est connu pour sa grande vitesse. Il est le cent-vingt-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/125.png'),
  ('126', 'Magmar', 'Feu', NULL, NULL, NULL, "Magmar est un Pokémon de type Feu. Il est connu pour sa flamme sur la tête. Il est le cent-vingt-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/126.png'),
  ('127', 'Scarabrute', 'Insecte', NULL, NULL, NULL, "Scarabrute est un Pokémon de type Insecte. Il est connu pour sa grande force. Il est le cent-vingt-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/127.png'),
  ('128', 'Tauros', 'Normal', NULL, NULL, NULL, "Tauros est un Pokémon de type Normal. Il est connu pour sa grande force. Il est le cent-vingt-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/128.png'),
  ('129', 'Magicarpe', 'Eau', NULL, '130', NULL, "Magicarpe est un Pokémon de type Eau. Il est connu pour sa faiblesse. Il est le cent-vingt-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/129.png'),
  ('130', 'Léviator', 'Eau', 'Vol', NULL, NULL, "Léviator est la forme évoluée de Magicarpe. Il est connu pour sa grande taille et sa force. Il est le cent-trentième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/130.png'),
  ('131', 'Lokhlass', 'Eau', 'Glace', NULL, NULL, "Lokhlass est un Pokémon de type Eau et Glace. Il est connu pour sa grande taille et sa force. Il est le cent-trente-et-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/131.png'),
  ('132', 'Métamorph', 'Normal', NULL, NULL, NULL, "Métamorph est un Pokémon de type Normal. Il est connu pour sa capacité à se transformer en d'autres Pokémon. Il est le cent-trente-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/132.png'),
  ('133', 'Évoli', 'Normal', NULL, '134', '135', "Évoli est un Pokémon de type Normal. Il est connu pour sa capacité à évoluer en plusieurs formes différentes. Il est le cent-trente-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/133.png'),
  ('134', 'Aquali', 'Eau', NULL, NULL, NULL, "Aquali est la forme évoluée d'Évoli. Il est connu pour sa grande force. Il est le cent-trente-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/134.png'),
  ('135', 'Voltali', 'Électrik', NULL, NULL, NULL, "Voltali est la forme évoluée d'Évoli. Il est connu pour sa grande vitesse. Il est le cent-trente-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/135.png'),
  ('136', 'Pyroli', 'Feu', NULL, NULL, NULL, "Pyroli est la forme évoluée d'Évoli. Il est connu pour sa flamme sur la tête. Il est le cent-trente-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/136.png'),
  ('137', 'Porygon', 'Normal', NULL, NULL, NULL, "Porygon est un Pokémon de type Normal. Il est connu pour sa forme en 3D. Il est le cent-trente-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/137.png'),
  ('138', 'Amonita', 'Roche', 'Eau', '139', NULL, "Amonita est un Pokémon de type Roche et Eau. Il est connu pour sa coquille en forme de spirale. Il est le cent-trente-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/138.png'),
  ('139', 'Amonistar', 'Roche', 'Eau', NULL, NULL, "Amonistar est la forme évoluée d'Amonita. Il est connu pour sa grande taille. Il est le cent-trente-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/139.png'),
  ('140', 'Kabuto', 'Roche', 'Eau', '141', NULL, "Kabuto est un Pokémon de type Roche et Eau. Il est connu pour sa carapace dure. Il est le cent-quarantième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/140.png'),
  ('141', 'Kabutops', 'Roche', 'Eau', NULL, NULL, "Kabutops est la forme évoluée de Kabuto. Il est connu pour ses lames acérées. Il est le cent-quarante-et-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/141.png'),
  ('142', 'Ptéra', 'Roche', 'Vol', NULL, NULL, "Ptéra est un Pokémon de type Roche et Vol. Il est connu pour sa grande taille et sa force. Il est le cent-quarante-deuxième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/142.png'),
  ('143', 'Ronflex', 'Normal', NULL, NULL, NULL, "Ronflex est un Pokémon de type Normal. Il est connu pour son appétit insatiable. Il est le cent-quarante-troisième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/143.png'),
  ('144', 'Artikodin', 'Glace', 'Vol', NULL, NULL, "Artikodin est un Pokémon de type Glace et Vol. Il est connu pour sa capacité à contrôler la glace. Il est le cent-quarante-quatrième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/144.png'),
  ('145', 'Électhor', 'Électrik', 'Vol', NULL, NULL, "Électhor est un Pokémon de type Électrik et Vol. Il est connu pour sa capacité à contrôler la foudre. Il est le cent-quarante-cinquième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/145.png'),
  ('146', 'Sulfura', 'Feu', 'Vol', NULL, NULL, "Sulfura est un Pokémon de type Feu et Vol. Il est connu pour sa capacité à contrôler le feu. Il est le cent-quarante-sixième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/146.png'),
  ('147', 'Minidraco', 'Dragon', NULL, '148', NULL, "Minidraco est un Pokémon de type Dragon. Il est connu pour sa petite taille. Il est le cent-quarante-septième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/147.png'),
  ('148', 'Draco', 'Dragon', NULL, '149', NULL, "Draco est la forme évoluée de Minidraco. Il est connu pour sa grande taille. Il est le cent-quarante-huitième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/148.png'),
  ('149', 'Dracolosse', 'Dragon', 'Vol', NULL, NULL, "Dracolosse est la forme évoluée de Draco. Il est connu pour sa grande taille et sa force. Il est le cent-quarante-neuvième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/149.png'),
  ('150', 'Mewtwo', 'Psy', NULL, NULL, NULL, "Mewtwo est un Pokémon de type Psy. Il est connu pour sa grande intelligence. Il est le cent-cinquantième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/150.png'),
  ('151', 'Mew', 'Psy', NULL, NULL, NULL, "Mew est un Pokémon de type Psy. Il est connu pour sa rareté et sa capacité à apprendre toutes les attaques. Il est le cent-cinquante-et-unième Pokémon du Pokédex de Kanto.", 'https://www.serebii.net/pokemongo/pokemon/151.png');
  

  INSERT INTO `stats` 
  VALUES 
  (1,45,49,49,65,65,45),
  (2,60,62,63,80,80,60),
  (3,80,82,83,100,100,80),
  (4,39,52,43,60,50,65),
  (5,58,64,58,80,65,80),
  (6,78,84,78,109,85,100),
  (7,44,48,65,50,64,43),
  (8,59,63,80,65,80,58),
  (9,79,83,100,85,105,78),
  (10,45,30,35,20,20,45),
  (11,50,20,55,25,25,30),
  (12,60,45,50,90,80,70),
  (13,40,35,30,20,20,50),
  (14,45,25,50,25,25,35),
  (15,65,90,40,45,80,75),
  (16,40,45,40,35,35,56),
  (17,63,60,55,50,50,71),
  (18,83,80,75,70,70,101),
  (19,30,56,35,25,35,72),
  (20,55,81,60,50,70,97),
  (21,40,60,30,31,31,70),
  (22,65,90,65,61,61,100),
  (23,35,60,44,40,54,55),
  (24,60,85,69,65,79,80),
  (25,35,55,40,50,50,90),
  (26,60,90,55,90,80,110),
  (27,50,75,85,20,30,40),
  (28,75,100,110,45,55,65),
  (29,55,47,52,40,40,41),
  (30,70,62,67,55,55,56),
  (31,90,92,87,75,85,76),
  (32,46,57,40,40,40,50),
  (33,61,72,57,55,55,65),
  (34,81,102,77,85,75,85),
  (35,70,45,48,60,65,35),
  (36,95,70,73,95,90,60),
  (37,38,41,40,50,65,65),
  (38,73,76,75,81,100,100),
  (39,115,45,20,45,25,20),
  (40,140,70,45,85,50,45),
  (41,40,45,35,30,40,55),
  (42,75,80,70,65,75,90),
  (43,45,50,55,75,65,30),
  (44,60,65,70,85,75,40),
  (45,75,80,85,110,90,50),
  (46,35,70,55,45,55,25),
  (47,60,95,80,60,80,30),
  (48,60,55,50,40,55,45),
  (49,70,65,60,90,75,90),
  (50,10,55,25,35,45,95),
  (51,35,80,50,50,70,120),
  (52,40,45,35,40,40,90),
  (53,65,70,60,65,65,115),
  (54,50,52,48,65,50,55),
  (55,80,82,78,95,80,85),
  (56,40,80,35,35,45,70),
  (57,65,105,60,60,70,95),
  (58,55,70,45,70,50,60),
  (59,90,110,80,100,80,95),
  (60,40,50,40,40,40,90),
  (61,65,65,65,50,50,90),
  (62,90,95,95,70,90,70),
  (63,25,20,15,105,55,90),
  (64,40,35,30,120,70,105),
  (65,55,50,45,135,95,120),
  (66,70,80,50,35,35,35),
  (67,80,100,70,50,60,45),
  (68,90,130,80,65,85,55),
  (69,50,75,35,70,30,40),
  (70,65,90,50,85,45,55),
  (71,80,105,65,100,70,70),
  (72,40,40,35,50,100,70),
  (73,80,70,65,80,120,100),
  (74,40,80,100,30,30,20),
  (75,55,95,115,45,45,35),
  (76,80,120,130,55,65,45),
  (77,50,85,55,65,65,90),
  (78,65,100,70,80,80,105),
  (79,90,65,65,40,40,15),
  (80,95,75,110,100,80,30),
  (81,25,35,70,95,55,45),
  (82,50,60,95,120,70,70),
  (83,52,65,55,58,62,60),
  (84,35,85,45,35,35,75),
  (85,60,110,70,60,60,100),
  (86,65,45,55,45,70,45),
  (87,90,70,80,70,95,70),
  (88,80,80,50,40,50,25),
  (89,105,105,75,65,100,50),
  (90,30,65,100,45,25,40),
  (91,50,95,180,85,45,70),
  (92,30,35,30,100,35,80),
  (93,45,50,45,115,55,95),
  (94,60,65,60,130,75,110),
  (95,35,45,160,30,45,70),
  (96,60,48,45,43,90,42),
  (97,85,73,70,73,115,67),
  (98,30,105,90,25,25,50),
  (99,55,130,115,50,50,75),
  (100,40,30,50,55,55,100),
  (101,60,50,70,80,80,140),
  (102,60,40,80,60,45,40),
  (103,95,95,85,125,65,55),
  (104,50,50,95,40,50,35),
  (105,60,80,110,50,80,45),
  (106,50,120,53,35,110,87),
  (107,50,105,79,35,110,76),
  (108,90,55,75,60,75,30),
  (109,40,65,95,60,45,35),
  (110,65,90,120,85,70,60),
  (111,80,85,95,30,30,25),
  (112,105,130,120,45,45,40),
  (113,250,5,5,35,105,50),
  (114,65,55,115,100,40,60),
  (115,105,95,80,40,80,90),
  (116,30,40,70,70,25,60),
  (117,55,65,95,95,45,85),
  (118,45,67,60,35,50,63),
  (119,80,92,65,65,80,68),
  (120,30,45,55,70,55,85),
  (121,60,75,85,100,85,115),
  (122,40,45,65,100,120,90),
  (123,70,110,80,55,80,105),
  (124,65,50,35,115,95,95),
  (125,65,83,57,95,85,105),
  (126,65,95,57,100,85,93),
  (127,65,125,100,55,70,85),
  (128,75,100,95,40,70,110),
  (129,20,10,55,15,20,80),
  (130,95,125,79,60,100,81),
  (131,130,85,80,85,95,60),
  (132,48,48,48,48,48,48),
  (133,55,55,50,45,65,55),
  (134,130,65,60,110,95,65),
  (135,65,65,60,110,95,130),
  (136,65,130,60,95,110,65),
  (137,65,60,70,85,75,40),
  (138,35,40,100,90,55,35),
  (139,70,60,125,115,70,55),
  (140,30,80,90,55,45,55),
  (141,60,115,105,65,70,80),
  (142,80,105,65,60,75,130),
  (143,160,110,65,65,110,30),
  (144,90,85,100,95,125,85),
  (145,90,90,85,125,90,100),
  (146,90,100,90,125,85,90),
  (147,41,64,45,50,50,50),
  (148,61,84,65,70,70,70),
  (149,91,134,95,100,100,80),
  (150,106,110,90,154,90,130),
  (151,100,100,100,100,100,100)